/* SPDX-License-Identifier: GPL-2.0-or-later */
#include "util/udev_rule.h"

void udev_rule_write(FILE *out, uint16_t vid, uint16_t pid, const UsbNode *node)
{
    const char *product = (node && node->product[0]) ? node->product : NULL;
    const char *serial = (node && node->serial[0]) ? node->serial : NULL;

    fprintf(out, "# Generated by usbexplorer for %04x:%04x%s%s\n",
            vid, pid, product ? " — " : "", product ? product : "");
    fprintf(out, "# Install as e.g. /etc/udev/rules.d/70-%04x-%04x.rules,\n",
            vid, pid);
    fprintf(out, "# then: sudo udevadm control --reload && sudo udevadm trigger\n\n");

    /* Primary rule: grant the seat's logged-in user access via uaccess. */
    fprintf(out,
            "SUBSYSTEM==\"usb\", ATTR{idVendor}==\"%04x\", ATTR{idProduct}==\"%04x\", "
            "TAG+=\"uaccess\"\n",
            vid, pid);

    /* Group/mode alternative for headless or multi-user setups. */
    fprintf(out,
            "# Alternative (group-based access):\n"
            "# SUBSYSTEM==\"usb\", ATTR{idVendor}==\"%04x\", ATTR{idProduct}==\"%04x\", "
            "MODE=\"0660\", GROUP=\"plugdev\"\n",
            vid, pid);

    if (serial)
        fprintf(out,
                "# Restrict to this one unit by serial number:\n"
                "# SUBSYSTEM==\"usb\", ATTR{idVendor}==\"%04x\", ATTR{idProduct}==\"%04x\", "
                "ATTR{serial}==\"%s\", TAG+=\"uaccess\"\n",
                vid, pid, serial);

    /* Stable symlink example for tooling that wants a fixed device path. */
    fprintf(out,
            "# Create a stable /dev symlink:\n"
            "# SUBSYSTEM==\"usb\", ATTR{idVendor}==\"%04x\", ATTR{idProduct}==\"%04x\", "
            "SYMLINK+=\"usb-%04x-%04x\"\n",
            vid, pid, vid, pid);
}
